-- MySQL Script generated by MySQL Workbench
-- Mon May 15 14:44:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema good_hands
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema good_hands
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `good_hands` DEFAULT CHARACTER SET utf8 ;
USE `good_hands` ;

-- -----------------------------------------------------
-- Table `good_hands`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `good_hands`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `good_hands`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `good_hands`.`tb_tema` (
  `id_tema` BIGINT NOT NULL AUTO_INCREMENT,
  `causa` VARCHAR(255) NOT NULL,
  `meta_arrecadacao` DOUBLE NOT NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `good_hands`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `good_hands`.`tb_postagem` (
  `id_postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `Imagem` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `arrecadacao` DOUBLE NOT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  `tb_tema_id_tema` BIGINT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) VISIBLE,
  UNIQUE INDEX `id_postagem_UNIQUE` (`id_postagem` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_tema1_idx` (`tb_tema_id_tema` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `good_hands`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_tema1`
    FOREIGN KEY (`tb_tema_id_tema`)
    REFERENCES `good_hands`.`tb_tema` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
